name = "GenericSchur"
uuid = "c145ed77-6b09-5dd9-b285-bf645a82121e"
version = "0.5.7-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixFactorizations = "a3b82374-2e81-5b9e-98ce-41277c0e4c87"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.3"
Aqua = "0.8"
GenericSVD = "0.3"
Libdl = "1"
LinearAlgebra = "1"
Printf = "1"
Random = "1"
SparseArrays = "1"
Test = "1"


[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
GenericSVD = "01680d73-4ee2-5a08-a1aa-533608c188bb"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Libdl", "GenericSVD", "SparseArrays", "Aqua"]
