[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[sources]
GenericSchur = {path = "/home/rasmith/julia-local/GenericSchur"}

[compat]
Documenter = "0.27"
